module.exports = {
    C: 'c',
    CPP: 'cpp',
    PYTHON: 'python',
    JAVA: 'java',
    NODEJS: 'nodejs',
    RUBY: 'ruby',
    TYPESCRIPT: 'typescript',
    GO: 'go',
    PHP: 'php',
    SWIFT: 'swift',
    RUST: 'rust',
    KOTLIN: 'kotlin',
    PERL: 'perl',
    HASKELL: 'haskell',
    SCALA: 'scala',
    LUA: 'lua',
    PROMPTV1: 'promptv1',
    PROMPTV2: 'promptv2',
    MULTIFILE: 'multifile',
    SQLITE3: 'sqlite3',
}
